# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graph.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgraph.proto\x12\x05graph\"\x15\n\x05Graph\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2@\n\x0cGraphService\x12\x30\n\x12SendAndModifyGraph\x12\x0c.graph.Graph\x1a\x0c.graph.Graphb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'graph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRAPH']._serialized_start=22
  _globals['_GRAPH']._serialized_end=43
  _globals['_GRAPHSERVICE']._serialized_start=45
  _globals['_GRAPHSERVICE']._serialized_end=109
# @@protoc_insertion_point(module_scope)
